# Generated by Django 3.2.8 on 2021-10-30 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='Last_name',
            new_name='last_name',
        ),
    ]
